# Usa una imagen base de Python
FROM python:alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY Client.py .
COPY main.py .

# Ejecuta el cliente
ENTRYPOINT ["python", "main.py"]
