# Usa una imagen base de Python
FROM python:alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY Server.py .
COPY main.py .

# Define las variables de entorno para HOST y PORT
ENV HOST=${HOST}
ENV PORT=${PORT}

# Instala las dependencias si las hay
# RUN pip install ...

# Ejecuta el servidor
CMD ["python", "main.py", HOST, PORT ]
